import { Bot, Building2, CreditCard, ShieldCheck, Users } from "lucide-react";
import { PageHeader, StatusBadge } from "@/components/ui";
import { requireManager } from "@/lib/auth/session";
import { prisma } from "@/lib/db/prisma";

export default async function SettingsPage() {
  const session = await requireManager();
  const shop = await prisma.shop.findUniqueOrThrow({ where: { id: session.user.shopId }, include: { users: { orderBy: { role: "asc" } } } });
  return <><PageHeader eyebrow="Configuration" title="Settings" description="Shop profile, users, notifications, AI, and payment integration status." /><div className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><div className="space-y-5"><section className="card p-5"><h2 className="flex items-center gap-2 font-bold"><Building2 className="size-4 text-brand" /> Shop profile</h2><div className="mt-5 grid gap-3 sm:grid-cols-2"><label className="text-xs font-bold">Shop name<input className="input mt-2" defaultValue={shop.name} readOnly /></label><label className="text-xs font-bold">Phone<input className="input mt-2" defaultValue={shop.phone || ""} readOnly /></label><label className="text-xs font-bold">Email<input className="input mt-2" defaultValue={shop.email || ""} readOnly /></label><label className="text-xs font-bold">Address<input className="input mt-2" defaultValue={shop.address || ""} readOnly /></label></div><p className="mt-3 text-xs text-muted">Profile editing can be enabled after connecting production identity and audit logging.</p></section><section className="card overflow-hidden"><div className="border-b p-5"><h2 className="flex items-center gap-2 font-bold"><Users className="size-4 text-brand" /> Team & roles</h2></div>{shop.users.map((u) => <div key={u.id} className="flex items-center justify-between border-t px-5 py-4 first:border-0"><div><p className="text-sm font-bold">{u.name}</p><p className="text-xs text-muted">{u.email}</p></div><StatusBadge status={u.role} /></div>)}</section></div><div className="space-y-5">{[{ icon: Bot, title: "OpenAI", ready: Boolean(process.env.OPENAI_API_KEY), detail: "Diagnostics, summaries, estimates, receptionist, and follow-up" }, { icon: CreditCard, title: "Stripe", ready: Boolean(process.env.STRIPE_SECRET_KEY), detail: "Test payments with automatic demo fallback" }, { icon: ShieldCheck, title: "Cloud SQL", ready: Boolean(process.env.DATABASE_URL), detail: "PostgreSQL over environment-controlled connection" }].map(({ icon: Icon, title, ready, detail }) => <section key={title} className="card p-5"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-emerald-50 text-brand"><Icon className="size-5" /></span><div className="flex-1"><p className="font-bold">{title}</p><p className="text-xs text-muted">{detail}</p></div><StatusBadge status={ready ? "CONNECTED" : "DEMO_FALLBACK"} /></div></section>)}</div></div></>;
}
