import { notFound } from "next/navigation";
import { AlertTriangle, Check, CheckCircle2, ShieldCheck, Wrench, X } from "lucide-react";
import { approveEstimate, payInvoice } from "@/app/actions";
import { prisma } from "@/lib/db/prisma";
import { money } from "@/lib/utils";

export const dynamic = "force-dynamic";
export default async function EstimatePortal({ params }: { params: Promise<{ token: string }> }) {
  const { token } = await params;
  const estimate = await prisma.estimate.findUnique({
    where: { portalToken: token },
    include: {
      shop: true, customer: true, vehicle: true, items: { orderBy: { sortOrder: "asc" } },
      repairOrder: { include: { diagnostics: { orderBy: { createdAt: "desc" }, take: 1 }, inspections: { include: { items: true }, orderBy: { createdAt: "desc" }, take: 1 }, invoice: true } },
    },
  });
  if (!estimate) notFound();
  const inspection = estimate.repairOrder.inspections[0];
  const diagnostic = estimate.repairOrder.diagnostics[0];
  return <main className="min-h-screen bg-[#eef4f3]">
    <header className="border-b bg-nav text-white"><div className="mx-auto flex max-w-4xl items-center justify-between px-5 py-5"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-[#21c3a7] font-black text-nav">Z</span><div><p className="font-black">ZOL</p><p className="text-[10px] text-white/60">{estimate.shop.name}</p></div></div><div className="text-right text-xs text-white/60"><p>{estimate.shop.phone}</p><p>{estimate.shop.email}</p></div></div></header>
    <div className="mx-auto max-w-4xl space-y-5 px-4 py-8 md:px-5">
      <section className="card overflow-hidden"><div className="bg-gradient-to-r from-[#133d38] to-[#176256] p-6 text-white md:p-8"><p className="text-xs font-bold uppercase tracking-[0.18em] text-emerald-200">Your repair estimate</p><h1 className="mt-2 text-3xl font-bold">{estimate.vehicle.year} {estimate.vehicle.make} {estimate.vehicle.model}</h1><p className="mt-2 text-sm text-white/65">{estimate.estimateNumber} · Prepared for {estimate.customer.firstName} {estimate.customer.lastName}</p></div><div className="grid gap-4 p-6 md:grid-cols-3"><div><p className="text-[11px] uppercase tracking-wider text-muted">Customer concern</p><p className="mt-1 text-sm font-semibold">{estimate.repairOrder.complaint}</p></div><div><p className="text-[11px] uppercase tracking-wider text-muted">Mileage</p><p className="mt-1 text-sm font-semibold">{estimate.repairOrder.mileageIn.toLocaleString()} miles</p></div><div><p className="text-[11px] uppercase tracking-wider text-muted">Status</p><p className="mt-1 text-sm font-semibold">{estimate.status.toLowerCase().replace("_", " ")}</p></div></div></section>

      {inspection && <section className="card p-6"><h2 className="flex items-center gap-2 font-bold"><ShieldCheck className="size-5 text-brand" /> Digital inspection</h2>{inspection.aiSummary && <p className="mt-3 rounded-xl bg-emerald-50 p-4 text-sm leading-6 text-emerald-900">{inspection.aiSummary}</p>}<div className="mt-4 grid gap-2 sm:grid-cols-2">{inspection.items.filter((i) => i.rating !== "NOT_INSPECTED").map((item) => <div key={item.id} className="flex items-start gap-3 rounded-xl border p-3"><span className={`mt-0.5 size-3 shrink-0 rounded-full ${item.rating === "GREEN" ? "bg-emerald-500" : item.rating === "YELLOW" ? "bg-amber-400" : "bg-red-500"}`} /><div><p className="text-sm font-bold">{item.category}</p><p className="text-xs leading-5 text-muted">{item.notes || item.name}</p></div></div>)}</div></section>}
      {diagnostic && <section className="card p-6"><h2 className="flex items-center gap-2 font-bold"><Wrench className="size-5 text-brand" /> Diagnostic summary</h2><p className="mt-3 text-sm leading-6 text-muted">Our technician recorded codes {diagnostic.obdCodes.join(", ") || "none"} and the following observations: {diagnostic.observations || diagnostic.symptoms}.</p><div className="mt-3 flex gap-2 rounded-xl bg-amber-50 p-3 text-xs text-amber-800"><AlertTriangle className="size-4 shrink-0" />AI assistance supports our process; all repair recommendations require technician verification.</div></section>}

      <section className="card overflow-hidden"><div className="border-b p-6"><h2 className="font-bold">Recommended work</h2><p className="mt-1 text-xs text-muted">Demo pricing is shown where live supplier pricing is not connected.</p></div><div>{estimate.items.map((item) => <div key={item.id} className="flex items-start gap-4 border-t px-6 py-4 first:border-0"><span className={`mt-0.5 grid size-6 shrink-0 place-items-center rounded-full ${item.approvalStatus === "APPROVED" ? "bg-emerald-100 text-emerald-700" : item.approvalStatus === "DECLINED" ? "bg-red-100 text-red-700" : "bg-slate-100 text-muted"}`}>{item.approvalStatus === "APPROVED" ? <Check className="size-3.5" /> : item.approvalStatus === "DECLINED" ? <X className="size-3.5" /> : "·"}</span><div className="flex-1"><p className="text-sm font-bold">{item.description}</p><p className="text-xs text-muted">{item.type.toLowerCase()} · Qty {Number(item.quantity)}</p></div><p className="font-bold">{money(item.total)}</p></div>)}</div><div className="border-t bg-[#f8fafa] p-6"><dl className="ml-auto max-w-xs space-y-2 text-sm"><div className="flex justify-between"><dt className="text-muted">Subtotal</dt><dd>{money(estimate.subtotal)}</dd></div><div className="flex justify-between"><dt className="text-muted">Tax</dt><dd>{money(estimate.tax)}</dd></div><div className="flex justify-between border-t pt-3 text-lg font-bold"><dt>Total</dt><dd>{money(estimate.total)}</dd></div></dl></div></section>

      {["SENT", "VIEWED"].includes(estimate.status) && <section className="card p-6"><h2 className="text-center text-lg font-bold">Ready to move forward?</h2><p className="mt-1 text-center text-sm text-muted">Your decision updates the shop immediately.</p><div className="mt-5 grid gap-3 sm:grid-cols-2"><form action={approveEstimate}><input type="hidden" name="portalToken" value={token} /><input type="hidden" name="decision" value="APPROVED" /><button className="btn btn-primary w-full"><CheckCircle2 className="size-4" /> Approve estimate</button></form><form action={approveEstimate}><input type="hidden" name="portalToken" value={token} /><input type="hidden" name="decision" value="DECLINED" /><button className="btn btn-secondary w-full text-red-600">Decline for now</button></form></div></section>}
      {estimate.status === "APPROVED" && !estimate.repairOrder.invoice && <div className="rounded-xl bg-emerald-100 p-5 text-center font-semibold text-emerald-900"><CheckCircle2 className="mr-2 inline size-5" />Approved — the shop has been notified.</div>}
      {estimate.repairOrder.invoice && estimate.repairOrder.invoice.status !== "PAID" && <section className="card p-6 text-center"><p className="text-xs uppercase tracking-wider text-muted">Invoice ready</p><p className="mt-2 text-3xl font-bold">{money(estimate.repairOrder.invoice.total)}</p><form action={payInvoice} className="mt-5"><input type="hidden" name="invoiceId" value={estimate.repairOrder.invoice.id} /><input type="hidden" name="portal" value={token} /><button className="btn btn-primary w-full sm:w-auto">Pay securely {process.env.STRIPE_SECRET_KEY ? "with Stripe" : "with demo payment"}</button></form></section>}
      {estimate.repairOrder.invoice?.status === "PAID" && <div className="rounded-xl bg-emerald-100 p-5 text-center font-semibold text-emerald-900"><CheckCircle2 className="mr-2 inline size-5" />Paid in full. Thank you!</div>}
      <p className="pb-5 text-center text-xs text-muted">Questions? Reply to your shop message or call {estimate.shop.phone}.</p>
    </div>
  </main>;
}
