import Link from "next/link";
import { ArrowRight, Bot, Sparkles } from "lucide-react";
import { PageHeader } from "@/components/ui";
import { requireManager } from "@/lib/auth/session";
import { answerShopQuestion } from "@/lib/ai/assistant";

export const dynamic = "force-dynamic";
const prompts = ["Which vehicles are waiting for customer approval?", "What vehicles are coming tomorrow?", "Which parts are still waiting to arrive?", "Which technicians have the highest workload?", "Which customers declined services?"];
export default async function AssistantPage({ searchParams }: { searchParams: Promise<{ q?: string }> }) {
  const session = await requireManager(); const { q } = await searchParams;
  const answer = q ? await answerShopQuestion(session.user.shopId, q) : null;
  return <><PageHeader eyebrow="Controlled intelligence" title="AI shop assistant" description="Ask operational questions. The assistant uses tenant-scoped, predefined server functions—never unrestricted generated SQL." /><div className="mx-auto max-w-3xl"><section className="card overflow-hidden"><div className="bg-gradient-to-r from-nav to-[#165b52] p-6 text-white"><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-xl bg-white/10"><Bot className="size-6 text-[#40d8bd]" /></span><div><h2 className="font-bold">ZOL Intelligence</h2><p className="text-xs text-white/60">Live answers from your shop data</p></div></div><form className="mt-5 flex gap-2 rounded-xl bg-white p-2"><input name="q" defaultValue={q} className="min-w-0 flex-1 px-2 text-sm text-foreground outline-none" placeholder="Ask about appointments, approvals, parts, workload..." required /><button className="btn btn-primary"><Sparkles className="size-4" /> Ask</button></form></div>{answer ? <div className="p-6"><p className="text-xs font-bold uppercase tracking-wider text-brand">{answer.title}</p><div className="mt-3 whitespace-pre-line text-sm leading-7">{answer.answer}</div>{answer.links.length > 0 && <div className="mt-5 flex flex-wrap gap-2">{answer.links.map((link) => <Link href={link.href} key={`${link.href}-${link.label}`} className="btn btn-secondary">{link.label}<ArrowRight className="size-3.5" /></Link>)}</div>}</div> : <div className="p-6"><p className="mb-3 text-xs font-bold uppercase tracking-wider text-muted">Try asking</p><div className="grid gap-2">{prompts.map((prompt) => <Link key={prompt} href={`/assistant?q=${encodeURIComponent(prompt)}`} className="flex items-center justify-between rounded-xl border px-4 py-3 text-sm hover:border-brand hover:text-brand">{prompt}<ArrowRight className="size-4" /></Link>)}</div></div>}</section><p className="mt-4 text-center text-xs text-muted">Answers are operational summaries, not financial or mechanical advice.</p></div></>;
}
